source 'https://rubygems.org'

# Inherit Rails version from parent gemfile (Appraisals) or use default
rails_version = ENV['RAILS_VERSION'] || '~> 8.0'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', rails_version
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem 'propshaft'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '>= 2.1'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# ActiveAdmin and dependencies
gem 'activeadmin', '~> 4.0.0.beta16'

# Our gem under test - load from parent directory
gem 'activeadmin_settings_cached', path: '../..'
gem 'rails-settings-cached', '>= 2.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'

  # Testing gems
  gem 'capybara', '~> 3.40'
  gem 'capybara-playwright-driver', '~> 0.5'
  gem 'database_cleaner-active_record', '~> 2.1'
  gem 'rspec-rails', '~> 6.0'
  gem 'rspec_junit_formatter'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'
end
